// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1605023880);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1605024000);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1605027120);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1605023640);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1605023760);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1604914091);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1605024120);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 199448);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1604913341);
user_pref("browser.laterrun.bookkeeping.sessionCount", 9);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b61358b1-03e6-4df5-bbdb-478c05e50949}");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1605028976059");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1605030758059");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1605023507637");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1605045107637");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200622191537");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1605029394");
user_pref("browser.slowStartup.averageTime", 3969);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20200622191537");
user_pref("browser.startup.homepage_override.mstone", "68.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1605029393);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.10.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Mon, 09 Nov 2020 16:49:18 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1605023881);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200622191537");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b38fa621-fadd-4ede-9905-1008c7ceb388\",\"fxmonitor@mozilla.org\":\"94e01b8a-a8dc-40d7-adbf-7418d24d3a64\",\"screenshots@mozilla.org\":\"9a6dcf1b-3277-4102-a0f8-ba36cbfd8cff\",\"webcompat-reporter@mozilla.org\":\"edaaa5ce-1ca3-4ab2-aeac-a484f2b32479\",\"webcompat@mozilla.org\":\"895cdd71-8388-47b2-be73-ce3d8143ba7d\",\"default-theme@mozilla.org\":\"5e5f231f-56cb-4e5f-a936-615b93c49972\",\"google@search.mozilla.org\":\"5c502bb0-989d-4dd0-801e-89abcfb419c8\",\"amazondotcom@search.mozilla.org\":\"3d78ff9c-1125-42ab-b735-37bc26ccf7d3\",\"bing@search.mozilla.org\":\"ae8670f1-2631-492a-812b-9df200aae05b\",\"ddg@search.mozilla.org\":\"623a4304-39b4-4bf0-99a0-5fe0dc1a2217\",\"ebay@search.mozilla.org\":\"51fdd439-510b-4068-abe5-0d73182e8c12\",\"twitter@search.mozilla.org\":\"a01a4fcb-87d3-4b71-8382-64eedc48cb40\",\"wikipedia@search.mozilla.org\":\"3b697d10-6033-43f7-9664-c5aea28d11a5\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1605025920);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1605023883);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200622191537");
user_pref("media.gmp-manager.lastCheck", 1605024381);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1604939258);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e9c663db-5f50-4f4e-8382-324395366bbc");
user_pref("security.sandbox.plugin.tempDirSuffix", "06cfa29a-c814-4145-9d4c-8a8e7ae205c6");
user_pref("services.blocklist.pinning.checked", 1605023765);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1605021343718\"");
user_pref("services.settings.last_update_seconds", 1605023765);
user_pref("services.settings.main.cfr-fxa.last_check", 1605023765);
user_pref("services.settings.main.cfr.last_check", 1605023765);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1605023765);
user_pref("services.settings.main.hijack-blocklists.last_check", 1605023765);
user_pref("services.settings.main.language-dictionaries.last_check", 1605023765);
user_pref("services.settings.main.sites-classification.last_check", 1605023765);
user_pref("services.settings.main.tippytop.last_check", 1605023765);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1605023765);
user_pref("services.settings.security.onecrl.checked", 1605023765);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1604939258);
user_pref("toolkit.startup.last_success", 1605029392);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200622191537");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
